name 'riak-cluster'
maintainer 'Irving Popovetsky'
maintainer_email 'irving@chef.io'
license 'all_rights'
description 'Installs/Configures riak-cluster'
long_description 'Installs/Configures riak-cluster'
version '0.1.0'

depends 'riak'
depends 'hostsfile'
depends 'chef-provisioning-vagrant-helper'
